### ISSUE TITLE
Conan Days banner is in the middle of page.

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-io.github.io#104]
Hi!

While reading the blog.conan.io page, I found the Conan Days banner in the middle of the page, waiting at the top. Is correct?

#### Environment
OS: Linux
Web Browser: Firefox 71.0 64-bit

![Screenshot_2020-01-07 Conan C C++ Package Manager](https://user-images.githubusercontent.com/4870173/71889221-72070a80-3120-11ea-8122-d044ab944922.png)

**Comment by memsharded** [comment]
It is fine, otherwise it reads much like a hero banner, this way we can offer content and links first, then the banner

**Comment by uilianries** [comment]
Understood, thanks for clarifying
