### ISSUE TITLE
Feedback on vcpkg integration

### ISSUE THREAD

**Issue by ras0219-msft** [conan-io/conan-io.github.io#17]
As requested via email; I have some feedback on https://github.com/conan-io/conan-io.github.io/commit/d51a9b24aac11419017781a24e283ea6086bd658.

First, I'm glad to see this initiative! We have purposefully provided an apt-get/brew-like interface to make integration with existing workflows as easy as possible, so I'm happy to see us being integrated in a similar manner.

**`system_requirements()` not used?**
I see at the top you've mentioned `system_requirements()` as the mechanism to use apt-get and brew packages, but I don't see anywhere else in the article where this is mentioned. Will Vcpkg packages be available with the same mechanism? I'm not incredibly familiar with your other system manager integration, but is binary repackaging the approach taken in the other cases? If not, why the different approach to Vcpkg?

**Tools folder**
Not a significant issue, but we currently have a separate `tools\` folder for executables; this enables us to deploy a single copy of the tool for release and debug and allows us to package more complex tools that may have very particular dependencies (by app-locally deploying the dependency DLLs). So, for now, `bin\` and `debug\bin\` will only contain DLLs.

**Fork/AppVeyor**
The AppVeyor.yml to automatically build your fork is awesome! This is an excellent approach to keep things sanely up-to-date while providing stability for your downstream users.

**Versioning interpretation**
I think there are some issues with the way you're currently interpreting the Vcpkg versions. Today, Vcpkg has the following versions:
```
PS> vcpkg search
...
boost                1.62             Peer-reviewed portable C++ source libraries
...
openssl              1.0.2h           OpenSSL is an open source project that provides a...
...
```

If we update `openssl` to a newer version (say, `1.1.0x`), we won't bump `boost`'s version, but we will rebuild them both. This means you'll now have two packages to choose from for `boost/1.62.0@lasote/vcpkg`; the one built against `openssl` version `1.1.0x` and also version `1.0.2h`. As far as I'm aware, conan doesn't allow that level of "overloading" on package name, so this causes a serious issue. If I have another package that depends on the old version of `openssl`, and I've asked both it and Boost to be installed, then I have a serious conundrum.

I see two possible resolutions with today's conan implementation. First, you could put a version in the channel (?): `boost/1.62@lasote/vcpkg_796e65ea73e883e275a7908c4214913d32d5327a`. Then, every package in the same channel is guaranteed to be built against each other by Vcpkg. However, this makes the package's version quite redundant since there will only ever be one version available. This leads to the other obvious implementation: use Vcpkg's version _as_ the library version. This makes it extremely easier for consumers to ensure they get matching versions -- pull the same version for all your dependencies!
```
boost/796e65ea73e883e275a7908c4214913d32d5327a@lasote/vcpkg
openssl/796e65ea73e883e275a7908c4214913d32d5327a@lasote/vcpkg
...etc...
```
[Note: I've used hashes above, but they're quite ugly to work with; it makes more sense to add tags to your fork and use those as versions. Perhaps dates like `conan-20161017` -- this would make it easy for customers to ensure they're always moving towards the latest version.]

Using hashes in this way also enables you to handle our mechanism for supporting multiple library versions: having separate Vcpkg enlistments with different portfiles (and therefore different SHAs). So if you wanted to use `boost/1.61.0`, you would generate a new surface of conan packages that would all inherit the SHA from the alternative enlistment.

**Conan benefits**
*Versioning*
I think it would be more productive to link directly to our explanation of how to use multiple versions (https://github.com/Microsoft/vcpkg/blob/master/docs/FAQ.md#how-do-i-use-different-versions-of-a-library-on-one-machine) and base the explanation off of that; I'm a bit confused about the exact differences here and I think other Vcpkg users would also be better able to understand the benefits when explained from this perspective as well!
*Older VS Versions*
We'd be interested in pulling this support upstream if you'd make a Pull Request!
*Automatic Linking*
This sounds a lot like our VS Integration! https://github.com/Microsoft/vcpkg/blob/master/docs/EXAMPLES.md#option-a-vs-project-user-wide-integration. We actually explicitly *don't* do this for CMake because of feedback about user expectations; we'd be happy to enable this as an option if there's demand!
*Binary Caching*
I think focusing on the conan-hosted-server aspect would be better here. We already cache the packages inside the Vcpkg enlistment itself (https://github.com/Microsoft/vcpkg/blob/master/docs/FAQ.md#will-vcpkg-support-downloading-compiled-binaries-from-a-public-or-private-server), so for corporate flows they already have a solution if they're willing to rehost the binaries themselves. I think the big benefit to using Conan is that you get your packages hosted as a service!
*Building from source*
I don't quite see how this is a benefit directly compared to using Vcpkg; it looks like an existing feature that conan continues to expose. Perhaps this is being miscategorized?

Overall, this looks really good. I think you may want to work further on the versioning aspect before pushing it as a blog post, however, since I'm almost certain this will cause a very poor user experience in the exact current implementation.

**Comment by lasote** [comment]
Thank you very much for your feedback!
We've released the blog post with some changes.

**Comment by Mizux** [comment]
link to update:
https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md#how-do-i-use-different-versions-of-a-library-on-one-machine

https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md#why-does-visual-studio-not-use-my-libraries-with-user-wide-integration-enabled

https://github.com/Microsoft/vcpkg/blob/master/docs/about/faq.md#will-vcpkg-support-downloading-compiled-binaries-from-a-public-or-private-server
