### ISSUE TITLE
Protobuf Python Example Looks Incorrect

### ISSUE THREAD

**Issue by apoggio** [conan-io/conan-io.github.io#185]
### Steps to reproduce (Include if Applicable)
In the last code section on https://blog.conan.io/2019/03/06/Serializing-your-data-with-Protobuf.html, the code
print("Sensor door: {}".format("Open" if sensor.temperature else "Closed"))
seems wrong.  Shouldn't the conditional be checking the value of sensor.door?

**Comment by memsharded** [comment]
Hi @apoggio !

Thanks for reporting this. I have moved the issue to the blog repo. As you can see it is open source too, would you like to contribute yourself a fix?

In any case, please note that such blog post is already quite old. Python-requires have got many changes, I strongly recommend  checking the docs: https://docs.conan.io/en/latest/extending/python_requires.html
