### ISSUE TITLE
Text bold format is not working

### ISSUE THREAD

**Issue by danimtb** [conan-io/conan-io.github.io#206]
See the image from the post https://blog.conan.io/2021/10/19/New-CMake-Transparent-Integration-Guide.html
![image](https://user-images.githubusercontent.com/10808592/139279108-45124200-dbd2-422e-abe0-914ddde142ed.png)
and the markdown text: https://github.com/conan-io/conan-io.github.io/blob/9d33645838d30a44383a6184cb159eb0f75fd246/_posts/2021-10-19-New-CMake-Transparent-Integration-Guide.markdown?plain=1#L346

The markdown renderer from GitHub is working fine though: https://github.com/conan-io/conan-io.github.io/blob/master/_posts/2021-10-19-New-CMake-Transparent-Integration-Guide.markdown#the-layout-method

**Comment by prince-chrismc** [comment]
Seems like this has been fixed 
![image](https://user-images.githubusercontent.com/16867443/195438037-71c7b74c-4292-48fe-b210-0f85c9a2e6a0.png)
