### ISSUE TITLE
[feature] Add notifications for cpplang slack

### ISSUE THREAD

**Issue by prince-chrismc** [conan-io/conan-io.github.io#234]
Following from the conversation in https://cpplang.slack.com/archives/C41CWV9HA/p1677145804583649, it would be very convenient to post to our Slack channel when new blogs are published.

This would help drive attention to the post for the folks who are most interested in it.

**Comment by MartinDelille** [comment]
I would suggest to use the same bot that the one used in the #qt room.

**Comment by memsharded** [comment]
Sure, good for me.

**Comment by prince-chrismc** [comment]
It's working 👏 

![image](https://github.com/conan-io/conan-io.github.io/assets/16867443/fc5c895e-9765-4db1-8c03-f45dc9e9a83f)
