### ISSUE TITLE
Broken images in May 23rd blog post

### ISSUE THREAD

**Issue by sourcedelica** [conan-io/conan-io.github.io#241]
I noticed two broken images in today's blog post.
<img width="374" alt="Screenshot 2023-05-23 at 9 27 47 AM" src="https://github.com/conan-io/conan-io.github.io/assets/4219652/31e06a02-c938-49fb-92b6-f78c8a8de12b">
<img width="511" alt="Screenshot 2023-05-23 at 9 28 08 AM" src="https://github.com/conan-io/conan-io.github.io/assets/4219652/2d26d845-d09f-464d-9b5f-e5ddb06a5562">

**Comment by czoido** [comment]
Thanks a lot for reporting @sourcedelica ! We are working to fix it
