### ISSUE TITLE
Add Time to Read

### ISSUE THREAD

**Issue by uilianries** [conan-io/conan-io.github.io#90]
Hi!

Some social medias like Medium offers a nice plugin called "Time-to-Read" which shows how much time is required to read the entire blog post:

![Screenshot_2019-09-27 Here’s how you can speedup Pandas with cuDF and GPUs](https://user-images.githubusercontent.com/4870173/65769708-9e1af480-e10a-11e9-847c-926ace22da1f.png)

It would be nice if Conan blog post could have the same plugin embedded:

![Screenshot_2019-09-27 Package ID modes control the ABI and the traceability of your dependencies](https://user-images.githubusercontent.com/4870173/65769812-e9350780-e10a-11e9-9f33-0f0b99a49882.png)

**Comment by danimtb** [comment]
closed by #91
